const instruct1 = `<ol><li>Heat a deep pot over medium heat. Add oil and butter. When butter is melted, add potatoes, celery, onion, bay leaves and chipotle peppers to the pot. Season vegetables with salt and pepper, mix well and saute until tender, about 10 minutes.</li><li>Sprinkle in flour and cook about 2 minutes, stirring constantly. Stir in clam juice and half and half and mix well.</li><li>Bring soup up to a simmer and continue to simmer for about 20 minutes, or until potatoes are soft.</li><li>Stir in corn, crab and sherry and simmer for another 5 minutes, until heated through.</li><li>Adjust the soup seasonings and remove the bay leaf.  Ladle soup into bowls and top with a few dashes of hot sauce, if desired.</li><li>Serve with some crackers, crusty bread or cornbread.</li></ol>`;
const instruct2 = `In a large saucepan, add the milk, cream and mint. Bring the mixture to a simmer over med-low heat and then turn the heat off. Let the mixture steep for 20 minutes at room temperature.\nStrain the mixture through a fine mesh sieve into a bowl and return to the saucepan. Add 3/4 cup of the sugar and bring to a simmer, whisking occasionally to dissolve the sugar.\nIn a medium bowl, whisk the remaining sugar and egg yolks until the mixture is slightly thickened and light in color. Slowly, add 1/4 cup of the milk mixture to the eggs while whisking constantly. Continue adding the milk to the egg mixture 1/4 cup at a time until all the ingredients are combined.\nPrepare and ice bath in a large bowl and place a medium bowl in the ice bath. Place a fine mesh stainer over the bowl.\nTransfer the cream mixture to a large saucepan and cook over medium heat, stirring constantly and scraping the bottom and sides with a heatproof spatula until the custard thickens enough to coat the back of a spoon. Strain the custard into the bowl and allow to cool.\nRefrigerate the custard until cold or overnight.\nPour the custard into the freezer can of an electric ice cream maker and freeze according to the manufacturer's instructions. When the ice cream is the consistency of soft serve, add the chocolate chips and allow to blend. Transfer to an airtight storage container and freeze.`;
const instruct3 = `<ol><li><span></span>Preheat oven to 350 degrees. Place a large skillet over medium heat; add two teaspoons of ghee or butter and let it melt. Sauté the shallots until they begin to lightly caramelize. Stir in the mushrooms, as well as some salt and pepper, and sauté until the mushrooms release their juices and turn golden brown.</li><li>Place a teaspoon of ghee in a pie plate or casserole dish; heat in the oven for about two minutes, or until the ghee is softened. Using a pastry brush, spread the melted ghee all around the inside of the baking dish. Add the mushroom and shallot mixture, then top with the crumbled goat cheese.</li><li>Using the back of a spoon, make four indentations in the mushroom mixture. Carefully crack an egg into each indentation. Top with salt, pepper, and herbes de Provence.</li><li>Bake for 18 to 23 minutes or until desired doneness. The whites should be cooked through but the yolks still soft. While the eggs are baking, toast the bread. Gently rub the toast with the cut side of the garlic clove until the bread is fragrant.</li><li>Remove the eggs from the oven. Top with fresh herbs or greens (I used baby arugula, but chopped chives would be fabulous, too) and serve with toast.</li></ol>`;
const instruct4 = `Bring the potatoes to a boil in a large pot of water. Reduce the heat to medium and cook until they are fork tender  about 10 to 12 minutes. Do not overcook. Drain well and let cool for 10 minutes or longer before transferring to a large bowl along with the peas, basil leaves and olives if using.To make the dressing, combine all the ingredients in a small blender or food processor and pulse into smooth. If it is too thick, add a bit more olive oil or almond milk. Taste for seasoning and adjust nutritional yeast, salt and pepper to taste. Toss the potatoes with the dressing and serve.`;
const instruct5 = `<p>Toast the dried coconut in a dry unoiled skillet or saucepan over medium-low heat, stirring or tossing frequently, for 8 to 10 minutes or until lightly browned.Combine the flour, coconut sugar, baking powder, baking soda and salt in a large mixing bowl. In a separate bowl, whisk together the almond milk, coconut oil, eggs and vanilla. Pour the milk and egg mixture into the dry ingredients and stir just until combined  do not overmix.Grease a non-stick skillet with coconut oil and heat over medium heat. When hot, add 1/3 cup of the pancake batter to the pan and scatter 1 tablespoon of the toasted coconut on top. Cook for 2 minutes or until browned on the bottom, then flip and cook for 1 more minute or until both sides are browned and the pancake is cooked throughout. Remove and continue cooking until the batter is used up.To make the sauce, combine 1 cup of the toasted coconut with the coconut milk and coconut sugar and bring to a boil. Reduce heat to medium-low and simmer, stirring frequently, for 20 minutes or until the sauce is thick. Remove from heat and let cool slightly. If desired, pour the sauce into a blender and process until smooth.*Notes: Use white sugar if you want a white sauce. The sauce can be made ahead of time and refrigerated  simply add a little water and reheat before serving.</p>`;
const instruct6 = `<ol><li>Place chopped thyme, lemon juice and zest and garlic in a glass bowl. Microwave on high heat for 30 seconds then let the herbs seep in the warm olive oil while you prepare the artichokes.</li><li>Prepare a large pot with an inch of water at the bottom and a steamer rack. Prepare the artichokes. Have lemon wedges ready. If you want a nice presentation, use scissors to snip away the pointy tips of the artichoke leaves. As you trim the artichokes, rub the cut areas with juice from the lemon wedges to prevent the artichokes from turning brown. Use a vegetable peeler to cut away the thick outer layer of the artichoke stems. Trim the stems to 2 inches from the base of the artichoke. Cut off and discard the top 1/2 inch of the artichokes. Cut the artichokes in half. Use a strong metal spoon to scoop out the fuzzy chokes and the small inner artichoke leaves. Rub lemon juice all over the inside and exposed cut areas of the artichokes.</li><li>Heat the water in the large pot with a steamer rack on high. When it comes to a boil, reduce the heat to medium high and place the artichoke halves, cut side down on the steam rack. Cover. Steam for 20 minutes or until you can easily pull off the outer leaves, and you can pierce the heart easily with a knife. The artichokes can be just a tiny bit less cooked than would be typically perfect for steamed artichokes, as you will be cooking them further on the grill.</li><li>Prepare your grill for direct, high heat. Toss the artichokes in the garlic, lemon and thyme infused oil coating liberally. Sprinkle artichokes with salt and pepper. Place the artichoke halves cut-side-down on the grill grates. Cover, and grill for 5 to 10 minutes, until you have nice grill mark on the cut sides of the artichokes.</li></ol>`;
const instruct7 = `Cut the pumpkin into large chunks, and place on a parchment or foil-lined baking sheet. Drizzle with oil and roast at 200C until fork-tender and golden.\nIn a blender mash the roasted pumpkin until smooth. Transfer into a soup pot.\nAdd cream, sour cream, wine and vegetable stock, stir and combine.\nBring the soup to a boil, then immediately remove from the flame.\nSprinkle with chopped fresh sage leaves serve with croutons`;

module.exports = {
  instruct1,
  instruct2,
  instruct3,
  instruct4,
  instruct5,
  instruct6,
  instruct7,
};
